package main

import "fmt"

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

func Problem002() {

	const limit	= 4000000

	var x, y, z, sum int

	fmt.Println("Problem #2")
	x = 1
	for  {
		z = y
		y = x
		x = y + z
		if x > limit {
			break
		}
		if x%2 == 0 {
			sum += x
		}
	}
	fmt.Println(sum)
}