package main

import "fmt"

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

func main() {

	const limit	= 100

	var x, y, z, sum int = 2, 1, 0, 0

	for x < limit {
		z = y
		y = x
		x = y + z

		fmt.Print(x)
		if x%2 == 0 {
			sum += x
			fmt.Println(" Even. Sum=", sum)
		}
	}
}